FROM ubuntu:24.04@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab

# Install system dependencies and development tools
# RUN apt-get update && \
#     apt-get install -y \
#         curl \
#         git \
#         build-essential \
#         python3 \
#         python3-pip \
#         ca-certificates \
#         gnupg \
#         lsb-release && \
#     curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
#     apt-get install -y nodejs && \
#     npm install -g pnpm && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y unzip